# Generated by Django 6.0.4 on 2026-04-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_error', models.CharField(max_length=200)),
                ('fecha_error', models.DateField()),
                ('cantidad_errores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricaFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulos', models.CharField(max_length=200)),
                ('parrafos', models.TextField()),
                ('botones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricaResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resultados', models.DateField()),
                ('estadisticas', models.IntegerField()),
            ],
        ),
    ]
